---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: quarkus-app
      labels:
        app: quarkus-app
    spec:
      ports:
        - name: http
          port: 8080
          targetPort: 8080
      selector:
        app: quarkus-app
      type: NodePort
  - apiVersion: apps/v1beta1
    kind: Deployment
    metadata:
      name: quarkus-app
      labels:
        app: quarkus-app
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: quarkus-app
      template:
        metadata:
          labels:
            app: quarkus-app
        spec:
          containers:
            - name: quarkus-app
              image: docker.pkg.github.com/a1brz/quarkus-app/quarkus-app-graalvm:latest
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
